title: Download and Install | Setup Canon Printer
description: Before browsing the stepwise procedure for ij.start.canon and install the Canon printer, let's first get familiar with the prerequisites to see upon before the procedure.
